name: omics-agent-env  # Name of the environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - fuzzywuzzy  # for intent matching of user queries
  - scikit-learn  # for ML-based functionalities
  - pandas  # for data handling
  - numpy  # for numerical computations
  - regex  # for regular expression support
  - nltk  # for natural language processing tasks
  - flask  # if you plan on deploying the agent as a web app later
  - pip:
      - spacy  # if you're using spaCy for NLP
      - transformers  # for advanced NLP models
